language: java
sudo: false
git:
  depth: 1
  submodules: true
cache:
  directories:
    - $HOME/.m2
notifications:
  irc:
    channels:
      - irc.freenode.net#georchestra
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
install: mvn install -DskipTests -P-all,travis -Dadditionalparam=-Xdoclint:none
script: mvn integration-test -P-all,travis -Dadditionalparam=-Xdoclint:none
addons:
  apt:
    packages:
      - ant
      - ant-optional
      - python-virtualenv
      - python-pip
